# Generated by Django 5.1.4 on 2026-09-29 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteImprenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(max_length=40, unique=True)),
                ('valores', models.JSONField(blank=True, default=dict)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ajuste de documentos',
                'verbose_name_plural': 'ajustes de documentos',
                'db_table': 'imprenta_ajuste',
            },
        ),
        migrations.CreateModel(
            name='VersionImprenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('foto', models.JSONField(default=dict)),
                ('resumen', models.JSONField(blank=True, default=list)),
                ('motivo', models.CharField(blank=True, default='', max_length=160)),
                ('restaurada_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imprenta.versionimprenta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'versión de los documentos',
                'verbose_name_plural': 'versiones de los documentos',
                'db_table': 'imprenta_version',
                'ordering': ['-creado_en', '-pk'],
            },
        ),
    ]
