# Generated by Django 5.1.4 on 2026-05-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaduria', '0002_seed_cuentas'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asiento',
            new_name='contaduria__fecha_61919e_idx',
            old_name='ctd_asiento_fc_idx',
        ),
        migrations.RenameIndex(
            model_name='asiento',
            new_name='contaduria__origen_8fdd93_idx',
            old_name='ctd_asiento_orig_idx',
        ),
        migrations.RenameIndex(
            model_name='partida',
            new_name='contaduria__cuenta__d3d6d5_idx',
            old_name='ctd_partida_cuenta_idx',
        ),
        migrations.AlterField(
            model_name='asiento',
            name='origen',
            field=models.CharField(choices=[('manual', 'Captura manual'), ('auto_ingreso', 'Automático · ingreso Tesorería'), ('auto_egreso', 'Automático · egreso Tesorería'), ('auto_anulacion_ingreso', 'Automático · anulación ingreso'), ('auto_anulacion_egreso', 'Automático · anulación egreso'), ('auto_factura_emitida', 'Automático · factura emitida'), ('auto_factura_cancelada', 'Automático · factura cancelada'), ('ajuste', 'Ajuste contable'), ('cierre', 'Cierre de periodo')], db_index=True, default='manual', max_length=30),
        ),
    ]
