# Generated by Django 5.1.4 on 2026-06-12 05:20

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaduria', '0007_cuentas_procesadores_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontable',
            name='codigo_agrupador_sat',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField(db_index=True)),
                ('hasta', models.DateField(db_index=True)),
                ('saldo_estado_cuenta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], db_index=True, default='abierta', max_length=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones', to='contaduria.cuentacontable')),
            ],
            options={
                'db_table': 'contaduria_conciliacion_bancaria',
                'ordering': ['-hasta', '-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='CierrePeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField(db_index=True)),
                ('hasta', models.DateField(db_index=True)),
                ('utilidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reabierto', models.BooleanField(db_index=True, default=False)),
                ('reabierto_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_reapertura', models.CharField(blank=True, default='', max_length=300)),
                ('asiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres', to='contaduria.asiento')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_creados', to=settings.AUTH_USER_MODEL)),
                ('reabierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_reabiertos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contaduria_cierre_periodo',
                'ordering': ['-hasta', '-creado_en'],
                'indexes': [models.Index(fields=['-hasta', '-creado_en'], name='contaduria__hasta_1c5968_idx')],
            },
        ),
        migrations.CreateModel(
            name='LineaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=300)),
                ('referencia', models.CharField(blank=True, default='', max_length=80)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('conciliada', models.BooleanField(db_index=True, default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contaduria.conciliacionbancaria')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_bancarias', to='contaduria.partida')),
            ],
            options={
                'db_table': 'contaduria_linea_bancaria',
                'ordering': ['conciliacion', 'fecha', 'orden', 'pk'],
                'indexes': [models.Index(fields=['conciliacion', 'conciliada'], name='contaduria__concili_18c927_idx')],
            },
        ),
    ]
