# Generated by Django 5.1.4 on 2026-09-29 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaduria', '0009_seed_agrupador_sat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='origen',
            field=models.CharField(choices=[('manual', 'Captura manual'), ('auto_ingreso', 'Automático · ingreso Tesorería'), ('auto_egreso', 'Automático · egreso Tesorería'), ('auto_anulacion_ingreso', 'Automático · anulación ingreso'), ('auto_anulacion_egreso', 'Automático · anulación egreso'), ('auto_factura_emitida', 'Automático · factura emitida'), ('auto_factura_cancelada', 'Automático · factura cancelada'), ('auto_reembolso', 'Automático · reembolso a empleado'), ('ajuste', 'Ajuste contable'), ('apertura', 'Saldos de arranque (carga contable)'), ('carga', 'Póliza importada (carga contable)'), ('cierre', 'Cierre de periodo')], db_index=True, default='manual', max_length=30),
        ),
        migrations.CreateModel(
            name='CargaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Vista previa'), ('aplicada', 'Aplicada'), ('deshecha', 'Deshecha')], db_index=True, default='borrador', max_length=12)),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=200)),
                ('archivo', models.BinaryField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('crear_desde_estados', models.BooleanField(default=True)),
                ('fecha_arranque', models.DateField(blank=True, null=True)),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('creados', models.JSONField(blank=True, default=dict)),
                ('ia', models.JSONField(blank=True, default=dict)),
                ('claves', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aplicada_en', models.DateTimeField(blank=True, null=True)),
                ('deshecha_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_deshacer', models.CharField(blank=True, default='', max_length=300)),
                ('aplicada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_contables_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_contables', to=settings.AUTH_USER_MODEL)),
                ('deshecha_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_contables_deshechas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contaduria_carga',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCuentaCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('contenido', models.BinaryField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_cuenta', to='contaduria.cargacontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados_cuenta_cargados', to='contaduria.cuentacontable')),
            ],
            options={
                'db_table': 'contaduria_carga_estado_cuenta',
                'ordering': ['carga', 'orden', 'pk'],
            },
        ),
    ]
