# Generated by Django 5.1.4 on 2026-05-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_ingreso_esperado',
            field=models.DateField(blank=True, help_text='Fecha en la que se espera cobrar el grueso del proyecto. Usada para proyecciones.', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='monto_cobrado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de lo efectivamente cobrado para este proyecto.', max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='monto_cotizado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto formal cotizado al cliente (puede diferir del estimado inicial).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='monto_facturado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de lo facturado al cliente para este proyecto.', max_digits=12),
        ),
    ]
