# Generated by Django 5.1.4 on 2026-06-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_fechas_con_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoproducto',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo por unidad para este proyecto. Vacío = usa el del catálogo.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proyectoproducto',
            name='merma',
            field=models.PositiveIntegerField(default=0, help_text='Piezas extra (muestras, control de calidad, regalos). Suman costo, no se cobran.'),
        ),
        migrations.AddField(
            model_name='proyectoproducto',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por unidad para este proyecto. Vacío = usa el del catálogo.', max_digits=12, null=True),
        ),
    ]
