# Generated by Django 5.1.4 on 2026-06-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_proveedor_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='iva_exento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyectoproducto',
            name='incluir_en_calculo',
            field=models.BooleanField(default=True),
        ),
    ]
