# Generated by Django 5.1.4 on 2026-09-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0038_recolorear_sin_descripcion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actividadproyecto',
            new_name='proyectos_a_proyect_9cb150_idx',
            old_name='proyectos_a_proyect_idx',
        ),
        migrations.AlterField(
            model_name='estadoproyecto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proyectoasignacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proyectoproducto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
