# Generated by Django 5.1.4 on 2026-05-21 03:29

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cotizacion',
            new_name='cotizacione_cliente_de59a8_idx',
            old_name='cotiz_cliente_creado_idx',
        ),
        migrations.RenameIndex(
            model_name='cotizacion',
            new_name='cotizacione_proyect_fa9c29_idx',
            old_name='cotiz_proyecto_creado_idx',
        ),
        migrations.RenameIndex(
            model_name='cotizacion',
            new_name='cotizacione_estado_aff4c5_idx',
            old_name='cotiz_estado_fecha_idx',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='anticipo_facturado_en',
            field=models.DateTimeField(blank=True, help_text='Cuando se generó la factura del anticipo desde esta cotización.', null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='anticipo_monto_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto absoluto del anticipo. Si se deja vacío, se calcula del porcentaje.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='anticipo_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% del total que se cobra como anticipo. 0 = sin anticipo.', max_digits=5),
        ),
    ]
