# Generated by Django 5.1.4 on 2026-09-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0020_cotizacion_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='notas_extra',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='notas_omitidas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
