# Generated by Django 5.1.4 on 2026-05-21 00:05

import apps.facturacion.models.factura
import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ajustes', '0002_tasa_impositiva'),
        ('cartera', '0002_cliente_slug'),
        ('cotizaciones', '0001_initial'),
        ('el_catalogo', '0001_initial'),
        ('proyectos', '0003_proyecto_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('cobrada_parcial', 'Cobrada parcial'), ('cobrada_total', 'Cobrada total'), ('cancelada', 'Cancelada')], db_index=True, default='borrador', max_length=20)),
                ('fecha_emision', models.DateField(default=datetime.date.today)),
                ('fecha_vencimiento', models.DateField(default=apps.facturacion.models.factura._vencimiento_default)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('descuento_global_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('notas', models.TextField(blank=True, default='')),
                ('terminos', models.TextField(blank=True, default='')),
                ('monto_cobrado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('emitida_en', models.DateTimeField(blank=True, null=True)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.CharField(blank=True, default='', max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_canceladas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='cartera.cliente')),
                ('cotizacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='cotizaciones.cotizacion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL)),
                ('emitida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_emitidas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'facturacion_factura',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='FacturaImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicado_en', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='facturacion.factura')),
                ('tasa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='ajustes.tasaimpositiva')),
            ],
            options={
                'db_table': 'facturacion_impuesto',
                'ordering': ['tasa__orden', 'tasa__nombre'],
            },
        ),
        migrations.CreateModel(
            name='FacturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('descripcion', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('unidad', models.CharField(default='pieza', max_length=30)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.factura')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_factura', to='el_catalogo.servicio')),
            ],
            options={
                'db_table': 'facturacion_item',
                'ordering': ['factura', 'orden', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente', '-creado_en'], name='facturacion_cliente_d48cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['proyecto', '-creado_en'], name='facturacion_proyect_2149bc_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado', '-fecha_emision'], name='facturacion_estado_8b8ae6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facturaimpuesto',
            unique_together={('factura', 'tasa')},
        ),
    ]
