# Generated by Django 5.1.4 on 2026-06-12 05:20

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_factura_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordatorioCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo', models.CharField(default='mora', max_length=20)),
                ('canal', models.CharField(blank=True, default='', max_length=10)),
                ('destinatario', models.EmailField(blank=True, default='', max_length=254)),
                ('dias_vencida', models.IntegerField(default=0)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ok', models.BooleanField(default=False)),
                ('detalle', models.CharField(blank=True, default='', max_length=300)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='facturacion.factura')),
            ],
            options={
                'db_table': 'facturacion_recordatorio_cobranza',
                'ordering': ['-enviado_en'],
                'indexes': [models.Index(fields=['factura', '-enviado_en'], name='facturacion_factura_55e4ce_idx')],
            },
        ),
    ]
