# Generated by Django 5.1.4 on 2026-08-24 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_regimen_default_honorarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CfdiEntrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(help_text='Folio fiscal del SAT. Único: evita archivar dos veces el mismo correo.', max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de asignar'), ('ligado', 'Ligado a su factura'), ('ignorado', 'Ignorado')], db_index=True, default='pendiente', max_length=16)),
                ('origen', models.CharField(default='correo', max_length=16)),
                ('emisor_rfc', models.CharField(blank=True, default='', max_length=20)),
                ('emisor_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('receptor_rfc', models.CharField(blank=True, default='', max_length=20)),
                ('receptor_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('moneda', models.CharField(blank=True, default='', max_length=8)),
                ('fecha_cfdi', models.CharField(blank=True, default='', max_length=40)),
                ('referencia', models.CharField(blank=True, default='', help_text='Serie y folio como los escribe quien lo emitió.', max_length=60)),
                ('motivo', models.CharField(blank=True, default='', max_length=300)),
                ('archivo_id', models.CharField(blank=True, default='', help_text='Dónde quedó guardado el XML.', max_length=255)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfdis_entrantes', to='facturacion.factura')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CFDI entrante',
                'verbose_name_plural': 'CFDI entrantes',
                'db_table': 'facturacion_cfdi_entrante',
                'ordering': ['-recibido_en'],
            },
        ),
    ]
