# Generated by Django 5.1.4 on 2026-05-15 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('orden', models.IntegerField(db_index=True, default=100)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'categoría de servicio',
                'verbose_name_plural': 'categorías de servicio',
                'db_table': 'catalogo_categoria',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150)),
                ('descripcion_default', models.TextField(blank=True, default='')),
                ('unidad', models.CharField(default='pieza', max_length=30)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='el_catalogo.categoriaservicio')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'db_table': 'catalogo_servicio',
                'ordering': ['categoria__orden', 'nombre'],
            },
        ),
    ]
