# Generated by Django 5.1.4 on 2026-09-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_catalogo', '0014_servicio_proveedor_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='variacion',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lo que cuesta fabricarlo o comprarlo, sin IVA.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='variacion',
            name='descripcion',
            field=models.CharField(blank=True, default='', help_text='Detalles cortos: tela, tamaño, color, etc.', max_length=500),
        ),
        migrations.AlterField(
            model_name='variacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='variacion',
            name='impresion_activa',
            field=models.BooleanField(default=False, help_text='Activar si esta variación lleva impresión.'),
        ),
        migrations.AlterField(
            model_name='variacion',
            name='impresion_descripcion',
            field=models.CharField(blank=True, default='', help_text='Detalles de la impresión (tintas, técnica, posición).', max_length=250),
        ),
        migrations.AlterField(
            model_name='variacion',
            name='nombre',
            field=models.CharField(help_text="Ej.: 'Talla M · algodón blanco · 1 tinta'.", max_length=150),
        ),
    ]
