# Generated by Django 5.1.4 on 2026-06-12 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartera', '0003_cliente_contacto'),
        ('el_catalogo', '0006_categoria_color'),
        ('proyectos', '0016_actividad_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('entrada_en', models.DateTimeField(blank=True, null=True)),
                ('entrada_lat', models.FloatField(blank=True, null=True)),
                ('entrada_lng', models.FloatField(blank=True, null=True)),
                ('entrada_precision', models.FloatField(blank=True, help_text='Metros', null=True)),
                ('entrada_sin_geo', models.BooleanField(default=False)),
                ('entrada_offline', models.BooleanField(default=False)),
                ('entrada_uuid', models.CharField(blank=True, default='', max_length=64)),
                ('salida_en', models.DateTimeField(blank=True, null=True)),
                ('salida_lat', models.FloatField(blank=True, null=True)),
                ('salida_lng', models.FloatField(blank=True, null=True)),
                ('salida_precision', models.FloatField(blank=True, help_text='Metros', null=True)),
                ('salida_sin_geo', models.BooleanField(default=False)),
                ('salida_offline', models.BooleanField(default=False)),
                ('salida_uuid', models.CharField(blank=True, default='', max_length=64)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('retardo_min', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checador_jornada',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SesionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_min', models.PositiveIntegerField(blank=True, help_text='Derivada al cerrar', null=True)),
                ('origen', models.CharField(choices=[('timer', 'Cronómetro'), ('manual', 'Captura manual')], default='timer', max_length=8)),
                ('nota', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada')], default='activa', max_length=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_checador', to='proyectos.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_proyecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checador_sesion_proyecto',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado_en', models.DateTimeField(help_text='Hora del dispositivo')),
                ('recibido_en', models.DateTimeField(auto_now_add=True, help_text='Hora del servidor')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, help_text='Metros', null=True)),
                ('sin_geo', models.BooleanField(default=False)),
                ('capturada_offline', models.BooleanField(default=False)),
                ('uuid_cliente', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('otro', 'Otro')], default='cliente', max_length=10)),
                ('nota', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_checador', to='cartera.cliente')),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='checador.jornada')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_checador', to='el_catalogo.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_checador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checador_visita',
                'ordering': ['-registrado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCorreccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Hora de entrada'), ('salida', 'Hora de salida'), ('visita', 'Hora de visita'), ('sesion', 'Sesión de proyecto')], max_length=10)),
                ('valor_propuesto', models.DateTimeField(help_text='Nuevo valor solicitado')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('comentario_admin', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones', to='checador.jornada')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_resueltas', to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones', to='checador.sesionproyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcciones_checador', to=settings.AUTH_USER_MODEL)),
                ('visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones', to='checador.visita')),
            ],
            options={
                'db_table': 'checador_correccion',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('tolerancia_min', models.PositiveIntegerField(default=15, help_text='Minutos antes de marcar retardo')),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Vacío = horario global default para todo el staff.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_laborales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checador_horario',
                'ordering': ['usuario_id', 'dia_semana'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'dia_semana'), name='checador_horario_usuario_dia')],
            },
        ),
        migrations.AddIndex(
            model_name='jornada',
            index=models.Index(fields=['usuario', 'fecha'], name='checador_jo_usuario_55ff3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='jornada',
            constraint=models.UniqueConstraint(fields=('usuario', 'fecha'), name='checador_jornada_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='sesionproyecto',
            index=models.Index(fields=['usuario', 'estado'], name='checador_se_usuario_f61859_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionproyecto',
            index=models.Index(fields=['proyecto', 'inicio'], name='checador_se_proyect_30ba10_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['usuario', 'registrado_en'], name='checador_vi_usuario_886dce_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['uuid_cliente'], name='checador_vi_uuid_cl_d966f0_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudcorreccion',
            index=models.Index(fields=['estado', 'creado_en'], name='checador_co_estado_0edfcc_idx'),
        ),
    ]
