# Generated by Django 5.1.4 on 2026-06-12 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checador', '0002_seed_horario_global'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordatorioEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_entrada_checador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checador_recordatorio_entrada',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'fecha'), name='checador_recordatorio_entrada_uniq')],
            },
        ),
    ]
