# Generated by Django 5.1.4 on 2026-06-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checador', '0003_recordatorioentrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='salida_automatica',
            field=models.BooleanField(default=False),
        ),
    ]
