# Generated by Django 5.1.4 on 2026-06-12 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checador', '0004_jornada_salida_automatica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='ajustado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jornada',
            name='ajustado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_ajustadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudcorreccion',
            name='fecha',
            field=models.DateField(blank=True, help_text='Día de la jornada (tipo jornada)', null=True),
        ),
        migrations.AddField(
            model_name='solicitudcorreccion',
            name='valor_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcorreccion',
            name='valor_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcorreccion',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Hora de entrada'), ('salida', 'Hora de salida'), ('visita', 'Hora de visita'), ('sesion', 'Sesión de proyecto'), ('jornada', 'Jornada completa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitudcorreccion',
            name='valor_propuesto',
            field=models.DateTimeField(blank=True, help_text='Nuevo valor solicitado', null=True),
        ),
    ]
