# Generated by Django 5.1.4 on 2026-09-29 21:59

import datetime
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('el_catalogo', '0015_alter_proveedor_id_alter_unidad_id_and_more'),
        ('proyectos', '0039_rename_proyectos_a_proyect_idx_proyectos_a_proyect_9cb150_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada al proveedor'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], db_index=True, default='borrador', max_length=12)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('fecha_entrega', models.DateField(blank=True, help_text='Para cuándo se necesita.', null=True)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('condiciones', models.TextField(blank=True, default='', help_text='Forma de pago, entrega, empaque…')),
                ('notas', models.TextField(blank=True, default='')),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('recibida_en', models.DateTimeField(blank=True, null=True)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='el_catalogo.proveedor')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'orden de compra',
                'verbose_name_plural': 'órdenes de compra',
                'db_table': 'compras_orden',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('unidad', models.CharField(blank=True, default='pz', max_length=30)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.ordencompra')),
            ],
            options={
                'db_table': 'compras_orden_item',
                'ordering': ['orden', 'pk'],
            },
        ),
    ]
