"""Catálogo tipado de eventos del Portavoz. Cada evento es un dataclass
serializable a JSON. Agrega aquí cualquier evento nuevo antes de emitirlo.

Regla #6: eventos tipados desde el día 1.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime
from typing import Any, Literal

from .fecha import ahora_mx

EventoTipo = Literal[
    "cliente.creado",
    "cliente.actualizado",
    "proyecto.creado",
    "proyecto.status_cambiado",
    "proyecto.codigo_renumerado",
    "proyecto.estado_creado",
    "proyecto.estado_actualizado",
    "proyecto.estado_borrado",
    "proyecto.egresos_generados",
    "proyecto.gasto_registrado",
    "chalan.voz_actualizada",
    "chalan.voz_personal_actualizada",
    "chalan.propuesta_generada",
    "chalan.aprendizaje_destilado",
    "chalan.analisis_negocio",
    "chalan.conocimiento_destilado",
    "tarea.creada",
    "tarea.completada",
    "tarea.recordatorio",
    "tarea.estado_creado",
    "tarea.estado_actualizado",
    "tarea.estado_borrado",
    "recordatorios.config_actualizada",
    "cotizacion.creada",
    "cotizacion.actualizada",
    "cotizacion.enviada",
    "cotizacion.aprobada",
    "cotizacion.rechazada",
    "cotizacion.anulada",
    "cotizacion.vencida",
    "cotizacion.pdf_generado",
    "cotizacion.generada",
    "cotizacion.pagada",
    "factura.emitida",
    "factura.vencida",
    "factura.pdf_generado",
    "pago.recibido",
    "pago.recordatorio",
    "usuario.creado",
    "usuario.bloqueado",
    "ajuste.credencial_guardada",
    "ajuste.cartero_configurado",
    "correo.solicitado",
    "correo.bienvenida_enviado",
    "correo.pago_enviado",
    "correo.enviado_chalan",
    "correo.campana_iniciada",
    "correo.campana_envio",
    "correo.campana_fallido",
    "correo.enviado",
    "correo.fallido",
    "ajuste.tasa_guardada",
    "ajuste.drive_probado",
    "ajuste.drive_conectado",
    "ajuste.drive_desconectado",
    "catalogo.servicio_creado",
    "catalogo.servicio_actualizado",
    "catalogo.servicio_quick_creado",
    "catalogo.unidad_creada",
    "catalogo.unidad_actualizada",
    "proveedor.creado",
    "proveedor.actualizado",
    "proveedor.archivado",
    "proveedor.reactivado",
    "proveedor.quick_creado",
    "proveedor.servicios_actualizados",
    "catalogo.variacion_creada",
    "mandado.estado_cambiado",
    "mandado.destino_fijado",
    "sidebar.orden_actualizado",
    "rol.creado",
    "rol.actualizado",
    "rol.borrado",
    "usuario.roles_extra_actualizados",
    "usuario.chalan_override_actualizado",
    "usuario.chalan_overrides_forzados",
    "usuario.presupuesto_ia_actualizado",
    "presupuesto_ia.rebasado",
    "presupuesto_ia.topado",
    "meta_kpi.actualizada",
    "buzon.nuevo_mensaje",
    "buzon.estado_cambiado",
    "buzon.respondido",
    "buzon.eliminado",
    "buzon.estado_creado",
    "buzon.estado_actualizado",
    "buzon.estado_borrado",
    "site.integracion_fallo",
    "deploy.iniciado",
    "deploy.exitoso",
    "deploy.rollback",
    "sesion.impersonacion_iniciada",
    "sesion.impersonacion_terminada",
    "auth.google_vinculada",
    "auth.google_error",
    "auth.google_cuenta_no_registrada",
    "recado.creado",
    "recado.editado",
    "recado.leido",
    "tesoreria.ingreso_registrado",
    "tesoreria.egreso_registrado",
    "tesoreria.ocr_procesado",
    "tesoreria.reembolso_pendiente",
    "tesoreria.ingreso_anulado",
    "tesoreria.egreso_anulado",
    "tesoreria.cuentas_por_pagar_alta",
    "tesoreria.exportado",
    "tesoreria.export_fallido",
    "centro_costo.creado",
    "centro_costo.actualizado",
    "contaduria.asiento_creado",
    "contaduria.asiento_anulado",
    "contaduria.cuenta_creada",
    "contaduria.cuenta_actualizada",
    "contaduria.periodo_cerrado",
    "contaduria.periodo_reabierto",
    "contaduria.conciliacion_creada",
    "contaduria.conciliacion_actualizada",
    "contaduria.exportado_xml",
    "cobranza.recordatorio_enviado",
    "cobranza.recordatorio_fallido",
    "ajuste.cobranza_configurada",
    "ajuste.fiscal_configurada",
    "checador.entrada",
    "checador.salida",
    "checador.visita",
    "checador.retardo",
    "checador.sesion_iniciada",
    "checador.sesion_cerrada",
    "checador.correccion_solicitada",
    "checador.correccion_resuelta",
    "checador.recordatorio_entrada",
    "checador.checada_fuera_geocerca",
    "checador.jornada_ajustada",
    "checador.horario_actualizado",
    "checador.exportado",
    "checador.sede_creada",
    "checador.sede_actualizada",
    "checador.sede_borrada",
    "checador.geocerca_configurada",
]


@dataclass
class EventoPortavoz:
    """Forma base de cualquier evento. Usa `tipo` literal para discriminar en n8n."""
    tipo: EventoTipo
    actor_id: int | None
    actor_email: str | None
    payload: dict[str, Any] = field(default_factory=dict)
    emitido_en: datetime = field(default_factory=ahora_mx)
    schema_version: int = 1

    def serializar(self) -> dict[str, Any]:
        d = asdict(self)
        d["emitido_en"] = self.emitido_en.isoformat()
        return d
