"""S-KPIs-V2: ConfigKPI, TableroKPI y MetaKPI con ámbito (despacho/persona/cliente).

Generada y depurada a mano: makemigrations agrega RenameIndex y AlterField(id)
espurios (§14). Sólo esquema; los datos van en la 0007 (Bug I).
"""

# Generated by Django 5.1.4 on 2026-09-29 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0008_razones_sociales'),
        ('cuentas', '0014_rol_y_roles_extra'),
        ('taller_home', '0005_snapshot_kpi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_slug', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('direccion', models.CharField(blank=True, choices=[('sube', 'Más es mejor'), ('baja', 'Menos es mejor'), ('neutro', 'Sólo informa')], default='', max_length=10)),
                ('umbral_amarillo', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('umbral_rojo', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'taller_home_config_kpi',
                'ordering': ['kpi_slug'],
            },
        ),
        migrations.CreateModel(
            name='TableroKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_slug', models.CharField(max_length=80)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'taller_home_tablero_kpi',
                'ordering': ['rol_id', 'orden', 'pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='metakpi',
            options={'ordering': ['kpi_slug', 'ambito', 'pk']},
        ),
        migrations.AddField(
            model_name='metakpi',
            name='ambito',
            field=models.CharField(choices=[('despacho', 'Todo el despacho'), ('persona', 'Una persona'), ('cliente', 'Un cliente')], default='despacho', max_length=10),
        ),
        migrations.AddField(
            model_name='metakpi',
            name='avisado_periodo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='metakpi',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metas_kpi', to='cartera.cliente'),
        ),
        migrations.AddField(
            model_name='metakpi',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metas_kpi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metakpi',
            name='kpi_slug',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='metakpi',
            name='periodo',
            field=models.CharField(choices=[('dia', 'Diario'), ('semana', 'Semanal'), ('mes', 'Mensual'), ('trimestre', 'Trimestral'), ('ano', 'Anual'), ('corte', 'Al corte')], default='mes', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='metakpi',
            constraint=models.UniqueConstraint(condition=models.Q(('ambito', 'despacho')), fields=('kpi_slug',), name='uniq_meta_kpi_despacho'),
        ),
        migrations.AddConstraint(
            model_name='metakpi',
            constraint=models.UniqueConstraint(condition=models.Q(('ambito', 'persona')), fields=('kpi_slug', 'usuario'), name='uniq_meta_kpi_persona'),
        ),
        migrations.AddConstraint(
            model_name='metakpi',
            constraint=models.UniqueConstraint(condition=models.Q(('ambito', 'cliente')), fields=('kpi_slug', 'cliente'), name='uniq_meta_kpi_cliente'),
        ),
        migrations.AddField(
            model_name='configkpi',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_kpi_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablerokpi',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tablero_kpis', to='cuentas.rol'),
        ),
        migrations.AddConstraint(
            model_name='tablerokpi',
            constraint=models.UniqueConstraint(fields=('rol', 'kpi_slug'), name='uniq_tablero_rol_kpi'),
        ),
        migrations.AddConstraint(
            model_name='tablerokpi',
            constraint=models.UniqueConstraint(condition=models.Q(('rol__isnull', True)), fields=('kpi_slug',), name='uniq_tablero_omision_kpi'),
        ),
    ]
