# Generated by Django 5.1.4 on 2026-05-15 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeBuzon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sugerencia', 'Sugerencia'), ('problema', 'Problema / bug'), ('otro', 'Otro')], db_index=True, max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('leido', 'Leído'), ('respondido', 'Respondido'), ('archivado', 'Archivado')], db_index=True, default='nuevo', max_length=20)),
                ('nota_interna', models.TextField(blank=True, default='')),
                ('respuesta_publica', models.TextField(blank=True, default='')),
                ('respondido_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_buzon', to=settings.AUTH_USER_MODEL)),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buzon_respondidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensaje del Buzón',
                'verbose_name_plural': 'mensajes del Buzón',
                'db_table': 'buzon_mensaje',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeBuzonCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.BigIntegerField(db_index=True)),
                ('proyecto_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('tipo', models.CharField(choices=[('sugerencia', 'Sugerencia'), ('problema', 'Problema / bug'), ('otro', 'Otro')], db_index=True, max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('leido', 'Leído'), ('respondido', 'Respondido'), ('archivado', 'Archivado')], db_index=True, default='nuevo', max_length=20)),
                ('nota_interna', models.TextField(blank=True, default='')),
                ('respuesta_publica', models.TextField(blank=True, default='')),
                ('respondido_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buzon_cliente_respondidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensaje del Buzón de Clientes',
                'verbose_name_plural': 'mensajes del Buzón de Clientes',
                'db_table': 'buzon_mensaje_cliente',
                'ordering': ['-creado_en'],
            },
        ),
    ]
