# Generated by Django 5.1.4 on 2026-05-19 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartera', '0002_cliente_slug'),
        ('proyectos', '0003_proyecto_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=300)),
                ('naturaleza', models.CharField(choices=[('proyecto', 'Asociable a proyecto'), ('operativo', 'Operación general'), ('mixto', 'Cualquiera')], default='mixto', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_costo_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tesoreria_centro_de_costo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('proveedor_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('estado_pago', models.CharField(choices=[('pagado', 'Pagado (saldado)'), ('por_reembolsar', 'Por reembolsar al empleado'), ('pendiente', 'Pendiente de pago')], db_index=True, default='pagado', max_length=20)),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia empresa'), ('tarjeta_empresa', 'Tarjeta empresa'), ('tarjeta_personal', 'Tarjeta personal (reembolso)'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='transferencia', max_length=30)),
                ('drive_file_id', models.CharField(blank=True, default='', max_length=100)),
                ('drive_url_view', models.URLField(blank=True, default='', max_length=500)),
                ('drive_url_thumbnail', models.URLField(blank=True, default='', max_length=500)),
                ('tiene_comprobante', models.BooleanField(default=False)),
                ('origen', models.CharField(choices=[('manual', 'Captura manual'), ('ocr', 'OCR de recibo'), ('dictado', 'Dictado El Chalán'), ('sala_juntas', 'Dictado desde Sala de Juntas')], default='manual', max_length=20)),
                ('confianza_ia', models.FloatField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anulado', models.BooleanField(db_index=True, default=False)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.CharField(blank=True, default='', max_length=300)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_anulados', to=settings.AUTH_USER_MODEL)),
                ('centro_de_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='tesoreria.centrodecosto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_capturados', to=settings.AUTH_USER_MODEL)),
                ('pagado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_que_pague', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to='proyectos.proyecto')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_que_solicite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tesoreria_egreso',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EgresoOcrLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(blank=True, default='', max_length=100)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=300)),
                ('tamano_original_bytes', models.BigIntegerField(default=0)),
                ('tamano_optimizado_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('chalan_usado', models.CharField(blank=True, default='', max_length=30)),
                ('modelo', models.CharField(blank=True, default='', max_length=80)),
                ('raw_extraccion', models.JSONField(blank=True, default=dict)),
                ('latencia_ms', models.IntegerField(default=0)),
                ('costo_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('fue_corregido', models.BooleanField(default=False)),
                ('correcciones', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_logs_creados', to=settings.AUTH_USER_MODEL)),
                ('egreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_logs', to='tesoreria.egreso')),
            ],
            options={
                'db_table': 'tesoreria_egreso_ocr_log',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia'), ('deposito', 'Depósito'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('stripe', 'Stripe'), ('mercadopago', 'MercadoPago'), ('otro', 'Otro')], default='transferencia', max_length=30)),
                ('referencia_externa', models.CharField(blank=True, default='', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anulado', models.BooleanField(db_index=True, default=False)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.CharField(blank=True, default='', max_length=300)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_anulados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='cartera.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_capturados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'tesoreria_ingreso',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='centrodecosto',
            index=models.Index(fields=['slug'], name='tesoreria_c_slug_06e173_idx'),
        ),
        migrations.AddIndex(
            model_name='centrodecosto',
            index=models.Index(fields=['activo'], name='tesoreria_c_activo_7ba547_idx'),
        ),
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(fields=['-fecha'], name='tesoreria_e_fecha_b9e0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(fields=['proyecto', '-fecha'], name='tesoreria_e_proyect_919266_idx'),
        ),
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(fields=['centro_de_costo', '-fecha'], name='tesoreria_e_centro__f611e4_idx'),
        ),
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(fields=['estado_pago'], name='tesoreria_e_estado__9ad24f_idx'),
        ),
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(fields=['pagado_por', 'estado_pago'], name='tesoreria_e_pagado__873c32_idx'),
        ),
        migrations.AddIndex(
            model_name='egresoocrlog',
            index=models.Index(fields=['-creado_en'], name='tesoreria_e_creado__15c1cc_idx'),
        ),
        migrations.AddIndex(
            model_name='egresoocrlog',
            index=models.Index(fields=['egreso'], name='tesoreria_e_egreso__dcd952_idx'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['-fecha'], name='tesoreria_i_fecha_88936c_idx'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['cliente', '-fecha'], name='tesoreria_i_cliente_fabb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['proyecto', '-fecha'], name='tesoreria_i_proyect_06c8e2_idx'),
        ),
    ]
