# Generated by Django 5.1.4 on 2026-05-21 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        ('tesoreria', '0002_seed_centros_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='facturacion.factura'),
        ),
    ]
