# Generated by Django 5.1.4 on 2026-05-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0003_ingreso_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='pagado_desde',
            field=models.CharField(blank=True, choices=[('', '—'), ('banco', 'Banco'), ('caja', 'Caja')], default='', help_text='De qué cuenta salió el dinero al ejecutar el pago.', max_length=20),
        ),
        migrations.AddField(
            model_name='egreso',
            name='pagado_en',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
