# Generated by Django 5.1.4 on 2026-05-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaImpositiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.CharField(choices=[('trasladado', 'Trasladado'), ('retencion', 'Retención')], db_index=True, max_length=20)),
                ('aplicable_default', models.BooleanField(default=False)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('orden', models.IntegerField(db_index=True, default=100)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tasa impositiva',
                'verbose_name_plural': 'tasas impositivas',
                'db_table': 'ajustes_tasa_impositiva',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
