# Generated by Django 5.1.4 on 2026-05-15 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0002_tasa_impositiva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalistaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(db_index=True, max_length=40)),
                ('provider', models.CharField(db_index=True, max_length=30)),
                ('modelo', models.CharField(blank=True, default='', max_length=80)),
                ('prompt_hash', models.CharField(db_index=True, max_length=64)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('costo_usd_estimado', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latencia_ms', models.IntegerField(default=0)),
                ('exito', models.BooleanField(db_index=True, default=False)),
                ('mensaje_error', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analistas_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log de Los Analistas',
                'verbose_name_plural': 'logs de Los Analistas',
                'db_table': 'ajustes_analistas_log',
                'ordering': ['-creado_en'],
            },
        ),
    ]
