# Generated by Django 5.1.4 on 2026-08-22 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _marcar_las_de_sistema(apps, schema_editor):
    """Las plantillas que ya existían las dispara el código: son de sistema.

    Idempotente. Se apoya en PLANTILLAS_DEFAULT en vez de una lista escrita a
    mano aquí, para que agregar una plantilla de sistema en el futuro no exija
    acordarse de esta migración.
    """
    from ajustes.plantillas_correo_default import PLANTILLAS_DEFAULT

    Plantilla = apps.get_model("ajustes", "PlantillaCorreo")
    Plantilla.objects.filter(slug__in=list(PLANTILLAS_DEFAULT)).update(
        sistema=True, origen="sistema",
    )


def _desmarcar(apps, schema_editor):
    Plantilla = apps.get_model("ajustes", "PlantillaCorreo")
    Plantilla.objects.update(sistema=False, origen="manual")


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0014_analisis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantillacorreo',
            options={'ordering': ['-sistema', 'nombre'], 'verbose_name': 'plantilla de correo', 'verbose_name_plural': 'plantillas de correo'},
        ),
        migrations.AddField(
            model_name='plantillacorreo',
            name='descripcion',
            field=models.CharField(blank=True, default='', help_text='Para qué sirve esta plantilla. Se ve al elegirla al enviar.', max_length=200),
        ),
        migrations.AddField(
            model_name='plantillacorreo',
            name='origen',
            field=models.CharField(choices=[('manual', 'Creada a mano'), ('chalan', 'Propuesta por El Chalán'), ('sistema', 'Del sistema')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='plantillacorreo',
            name='remitente_email',
            field=models.EmailField(blank=True, default='', help_text='Alias desde el que sale este correo, ej. cobranza@learningcenter.mx. Vacío = el remitente general. El alias debe estar dado de alta en «Enviar como» de la cuenta de correo, o Gmail lo reescribe.', max_length=254),
        ),
        migrations.AddField(
            model_name='plantillacorreo',
            name='remitente_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre visible de este remitente, ej. «Cobranza Learning Center».', max_length=120),
        ),
        migrations.AddField(
            model_name='plantillacorreo',
            name='sistema',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='plantillacorreo',
            name='activa',
            field=models.BooleanField(default=True, help_text='Una plantilla apagada no aparece al enviar ni la usa ninguna regla.'),
        ),
        migrations.CreateModel(
            name='ReglaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('proyecto_estado', 'Un proyecto cambia de estado'), ('cotizacion_aprobada', 'El cliente aprueba una cotización'), ('mandado_entregado', 'Se marca una entrega como entregada'), ('cliente_dormido', 'Un cliente lleva tiempo sin proyectos nuevos')], db_index=True, max_length=30)),
                ('activa', models.BooleanField(default=False, help_text='Arranca apagada a propósito: enciéndela cuando la plantilla esté lista.')),
                ('estado_slug', models.SlugField(blank=True, default='', help_text='Sólo para «cambia de estado»: qué estado dispara el aviso.', max_length=40)),
                ('dias', models.PositiveIntegerField(default=90, help_text='Sólo para «cliente dormido»: días de silencio antes de escribirle.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_correo_creadas', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(help_text='Plantilla que se manda cuando ocurre el evento.', on_delete=django.db.models.deletion.PROTECT, related_name='reglas', to='ajustes.plantillacorreo')),
            ],
            options={
                'verbose_name': 'regla de correo',
                'verbose_name_plural': 'reglas de correo',
                'db_table': 'ajustes_regla_correo',
                'ordering': ['evento', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CorreoEnviadoRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(db_index=True, max_length=120)),
                ('destinatario', models.EmailField(max_length=254)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviados', to='ajustes.reglacorreo')),
            ],
            options={
                'db_table': 'ajustes_correo_enviado_regla',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='reglacorreo',
            constraint=models.UniqueConstraint(fields=('evento', 'estado_slug'), name='regla_correo_unica_por_evento_y_estado'),
        ),
        migrations.AddConstraint(
            model_name='correoenviadoregla',
            constraint=models.UniqueConstraint(fields=('regla', 'referencia'), name='correo_regla_una_vez_por_referencia'),
        ),
        migrations.RunPython(_marcar_las_de_sistema, _desmarcar),
    ]
