# Generated by Django 5.1.4 on 2026-08-22 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0015_plantillas_libres_y_reglas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasRemitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre visible sugerido, ej. «Cobranza Learning Center».', max_length=120)),
                ('verificado', models.BooleanField(default=False, help_text='Marcado a mano tras mandar una prueba y comprobar de quién llegó.')),
                ('verificado_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, default='', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias_verificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alias de remitente',
                'verbose_name_plural': 'alias de remitente',
                'db_table': 'ajustes_alias_remitente',
                'ordering': ['email'],
            },
        ),
    ]
