# Generated by Django 5.1.4 on 2026-08-24 16:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Sólo CreateModel: el `AlterField` de BigAutoField que genera `makemigrations`
# es uno de los espurios conocidos del repo (§14) y se quita a mano. Y NO lleva
# data migration a propósito — la fila se crea al leerla con `obtener()`, porque
# insertar en la misma tabla cuyo índice acaba de crearse es lo que tumbó el
# arranque el 2026-08-23 (§14 Bug I).


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0021_sembrar_remitente_chalan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(choices=[('auto', 'Automático — Chromium si está disponible, si no Google'), ('gotenberg', 'Sólo Chromium (aquí en el servidor)'), ('google', 'Sólo Google Docs (como antes)')], default='auto', help_text='Quién arma el PDF. Déjalo en automático salvo que estés diagnosticando algo: Chromium respeta los márgenes y numera las páginas de verdad; Google es el camino anterior.', max_length=16)),
                ('tamano_papel', models.CharField(choices=[('carta', 'Carta (21.6 × 27.9 cm)'), ('oficio', 'Oficio (21.6 × 33 cm)'), ('a4', 'A4 (21 × 29.7 cm)')], default='carta', help_text='Tamaño de la hoja. En México casi todo va en carta.', max_length=10)),
                ('margen_superior_pt', models.PositiveSmallIntegerField(default=36, help_text='Aire entre el borde de arriba y donde empieza el logotipo. 36 son media pulgada; 72, una pulgada.', validators=[django.core.validators.MaxValueValidator(216)])),
                ('margen_inferior_pt', models.PositiveSmallIntegerField(default=43, help_text='Aire hasta el borde de abajo. El pie de página vive dentro de este margen.', validators=[django.core.validators.MaxValueValidator(216)])),
                ('margen_izquierdo_pt', models.PositiveSmallIntegerField(default=72, help_text='Margen izquierdo. Súbelo si el documento se va a engargolar.', validators=[django.core.validators.MaxValueValidator(216)])),
                ('margen_derecho_pt', models.PositiveSmallIntegerField(default=72, help_text='Margen derecho.', validators=[django.core.validators.MaxValueValidator(216)])),
                ('pie_texto', models.CharField(blank=True, default='', help_text='Texto chico al pie de cada hoja, alineado a la izquierda. Déjalo vacío si no quieres ninguno.', max_length=120)),
                ('numerar_paginas', models.BooleanField(default=True, help_text='Muestra «1/3» a la derecha del pie. Con Chromium el número avanza de verdad; con Google todas las hojas dirían «1/1», que es la razón por la que este ajuste existe.')),
                ('interlineado', models.DecimalField(decimal_places=2, default=1.02, help_text='Qué tan pegados van los renglones. 1.02 es lo más apretado que se puede sin que los acentos se encimen; 1.5 es holgado.', max_digits=3, validators=[django.core.validators.MinValueValidator(0.8), django.core.validators.MaxValueValidator(2.0)])),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'configuración de documentos',
                'verbose_name_plural': 'configuración de documentos',
                'db_table': 'ajustes_config_documento',
            },
        ),
    ]
