# Generated by Django 5.1.4 on 2026-08-24 17:57

from django.db import migrations, models

# Sólo los dos AddField: el `AlterField` de BigAutoField que genera
# `makemigrations` es uno de los espurios conocidos del repo (§14).


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0022_configuracion_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciondocumento',
            name='encabezado_texto',
            field=models.CharField(blank=True, default='', help_text='Texto chico arriba de cada hoja, alineado a la derecha. Útil para el nombre del despacho o un teléfono. Vacío = sin encabezado.', max_length=120),
        ),
        migrations.AddField(
            model_name='configuraciondocumento',
            name='marca_borrador',
            field=models.CharField(blank=True, default='BORRADOR', help_text='Se estampa cruzada en las cotizaciones que aún no se han enviado, para que no se confundan con las que ya salieron. Vacío = sin marca.', max_length=30),
        ),
    ]
